language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.sonar/cache

addons:
  sonarcloud:
    organization: fbertolotti
    token: $SONAR_TOKEN

install:
  - git fetch --unshallow
  - composer remove "friendsofphp/php-cs-fixer" --dev --no-interaction
  - composer install --no-scripts --no-progress --no-interaction

script:
  - |
    ./vendor/bin/phpunit \
      --log-junit junit.xml \
      --coverage-clover clover.xml \
      --configuration phpunit.xml.dist
  - |
    [ "$TRAVIS_PHP_VERSION" != "hhvm" ] \
    && [ "$TRAVIS_PHP_VERSION" != "nightly" ] \
    && sonar-scanner \
      "-Dsonar.projectVersion=$(git describe --tags)_PHP-$TRAVIS_PHP_VERSION" \
      "-Dsonar.projectKey=Rune" \
      "-Dsonar.projectName=Rune" \
      "-Dsonar.projectKey=Rune" \
      "-Dsonar.php.tests.reportPath=junit.xml" \
      "-Dsonar.php.coverage.reportPaths=clover.xml" \
      "-Dsonar.sources=src" \
      "-Dsonar.tests=test" \
    || true
